name: CodeCov

on: [pull_request]

jobs:
  python-codecov:
    runs-on: ubuntu-latest
    name: CodeCov
    steps:
    - name: checkout source repo
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m pytest -vv

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1