name: CodeCov

on: [pull_request]

jobs:
  python-codecov:
    runs-on: ubuntu-latest
    name: CodeCov
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Generate Report
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        coverage run -m pytest -vv

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
