name: Linter

on: [pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.1.0
      with:
          mypy-flags: '--ignore-missing-imports'